### ISSUE TITLE
Orbi integration

### ISSUE THREAD

**Issue by subcritical71** [agneevX/my-ha-setup#11]
I recently started to implement your orbi integration into my HA setup but I see you have now removed the information. I know I can go back into history and get the data, but is there a reason you did this (out of date, no longer working, etc)? 

The one problem I was having and was starting to tackle today is the command_line code;
```
- platform: command_line
  name: Orbi Router vnstat (total)
  command: "/bin/bash /home/homeassistant/scripts/orbi_router.sh vnstat_total"
  # Script in ./bash_scripts/orbi_router.sh
  scan_interval: 120
  value_template: "{{ (value_json.id) }}"
  json_attributes:
    - rx
    - tx
```

My thinking is I don't have the proper sh script installed...

Anyway, thanks for putting this information out there as it helps a noob like me.
